name = "liteping-web"
compatibility_date = "2025-12-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "liteping-db"
database_id = "f83fd4e9-8d94-4430-8389-d417aaa7b2f6"
